version: "3.9"

services:
  mysql:
    build: mysql
    environment:
      MYSQL_DATABASE: bookstore
      MYSQL_ROOT_PASSWORD: admin
    ports:
      - 3306:3306
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    volumes:
      - mysql_data:/var/lib/mysql

  api:
    build: api
    restart: always
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      MYSQL_HOST: mysql
      MYSQL_PORT: 3306
      MYSQL_USER: root
      MYSQL_PASS: admin
      MYSQL_DB_NAME: bookstore
    ports:
      - 7950:9000

volumes:
  mysql_data:
