apiVersion: v1
kind: Service
metadata:
  labels:
    service: api
  name: api
spec:
  ports:
    - name: api-port
      port: 7950
      targetPort: 9000
      nodePort: 4000
  type: NodePort
  selector:
    service: api
